-- MySQL Script generated by MySQL Workbench
-- Tue Aug 10 16:47:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetofinal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetofinal` ;

-- -----------------------------------------------------
-- Schema projetofinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetofinal` DEFAULT CHARACTER SET utf8 ;
USE `projetofinal` ;

-- -----------------------------------------------------
-- Table `projetofinal`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetofinal`.`pessoa` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `dataNasc` DATETIME NOT NULL,
  PRIMARY KEY (`cpf`, `nome`, `dataNasc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetofinal`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetofinal`.`medico` (
  `crm` VARCHAR(45) NOT NULL,
  `especializacao` VARCHAR(45) NOT NULL,
  `disponivel` TINYINT NOT NULL,
  `pessoa_cpf` INT NOT NULL,
  `pessoa_nome` VARCHAR(45) NOT NULL,
  `pessoa_dataNasc` DATETIME NOT NULL,
  PRIMARY KEY (`crm`),
  INDEX `fk_medico_pessoa1_idx` (`pessoa_cpf` ASC, `pessoa_nome` ASC, `pessoa_dataNasc` ASC) VISIBLE,
  CONSTRAINT `fk_medico_pessoa1`
    FOREIGN KEY (`pessoa_cpf` , `pessoa_nome` , `pessoa_dataNasc`)
    REFERENCES `projetofinal`.`pessoa` (`cpf` , `nome` , `dataNasc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetofinal`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetofinal`.`paciente` (
  `telefone` INT NOT NULL,
  `gravidade` INT NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `pacientecol` VARCHAR(45) NOT NULL,
  `proximo` VARCHAR(45) NOT NULL,
  `hora_chegada` DATETIME NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_cpf` INT NOT NULL,
  `pessoa_nome` VARCHAR(45) NOT NULL,
  `pessoa_dataNasc` DATETIME NOT NULL,
  `pessoa_pessoacol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paciente_pessoa1_idx` (`pessoa_cpf` ASC, `pessoa_nome` ASC, `pessoa_dataNasc` ASC, `pessoa_pessoacol` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_pessoa1`
    FOREIGN KEY (`pessoa_cpf` , `pessoa_nome` , `pessoa_dataNasc`)
    REFERENCES `projetofinal`.`pessoa` (`cpf` , `nome` , `dataNasc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetofinal`.`atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetofinal`.`atendimento` (
  `horario_atendimento` DATETIME NOT NULL,
  `paciente_id` INT NOT NULL,
  `medico_crm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`paciente_id`, `medico_crm`),
  INDEX `fk_atendimento_medico1_idx` (`medico_crm` ASC) VISIBLE,
  CONSTRAINT `fk_atendimento_paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `projetofinal`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendimento_medico1`
    FOREIGN KEY (`medico_crm`)
    REFERENCES `projetofinal`.`medico` (`crm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
