-- MySQL Script generated by MySQL Workbench
-- Tue Aug 17 08:09:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetofinal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetofinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetofinal` DEFAULT CHARACTER SET utf8 ;
USE `projetofinal` ;

-- -----------------------------------------------------
-- Table `projetofinal`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetofinal`.`medico` (
  `crm` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `disponivel` TINYINT NOT NULL,
  PRIMARY KEY (`crm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetofinal`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetofinal`.`paciente` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `proximo` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetofinal`.`atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetofinal`.`atendimento` (
  `horario_atendimento` DATETIME NOT NULL,
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `medico_crm` VARCHAR(45) NOT NULL,
  `paciente_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`, `medico_crm`, `paciente_cpf`),
  INDEX `fk_atendimento_medico1_idx` (`medico_crm` ASC) VISIBLE,
  INDEX `fk_atendimento_paciente1_idx` (`paciente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_atendimento_medico1`
    FOREIGN KEY (`medico_crm`)
    REFERENCES `projetofinal`.`medico` (`crm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendimento_paciente1`
    FOREIGN KEY (`paciente_cpf`)
    REFERENCES `projetofinal`.`paciente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetofinal`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetofinal`.`usuario` (
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `senhaUsuario` VARCHAR(45) NOT NULL,
  `tipoUsuario` INT NOT NULL,
  UNIQUE INDEX `nomeUsuario_UNIQUE` (`nomeUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetofinal`.`prontoSocorro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetofinal`.`prontoSocorro` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `hora_chegada` DATETIME NOT NULL,
  `hora_atendimento` DATETIME NOT NULL,
  `medico_crm` VARCHAR(45) NOT NULL,
  `paciente_cpf` VARCHAR(45) NOT NULL,
  `gravidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`, `paciente_cpf`, `medico_crm`),
  INDEX `fk_prontoSocorro_medico1_idx` (`medico_crm` ASC) VISIBLE,
  INDEX `fk_prontoSocorro_paciente1_idx` (`paciente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_prontoSocorro_medico1`
    FOREIGN KEY (`medico_crm`)
    REFERENCES `projetofinal`.`medico` (`crm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prontoSocorro_paciente1`
    FOREIGN KEY (`paciente_cpf`)
    REFERENCES `projetofinal`.`paciente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
